### ISSUE TITLE
riemann-kafka consumer commits per message leads to low performance

### ISSUE THREAD

**Issue by liuweichu** [pyr/riemann-kafka#9]
For now the consumer will commit offset for every message from kafka message stream.
This results a very poor performance since it commits to zk rapidly and zk are strongly consistent across its quorum ([a random stackoverflow reference](http://stackoverflow.com/questions/25293622/kafka-how-to-commit-offset-after-every-message-using-high-level-consumer))

In our test, if riemann consumer talks to a standalone zk, it can only consuming 1000 msgs/s. If riemann talks to a 3-zk quorum, it can only consume 500 msgs/s and the CPU wait goes to 50% on each zk VMs.

If we don't commit offset at all (not really a correct way to fix this problem though), one consumer can consume around 10k msgs/s.

**Comment by pyr** [comment]
Hi @liuweichu,

May I ask what version of the kafka broker you are using? I'm thinking of moving the code to rely on https://pyr.github.io/kinsky, but that will enforce a dependency on 0.9.0 brokers.

**Comment by liuweichu** [comment]
@pyr 

Thank you for reply.
That is a really exciting news for us.
Currently we are on 0.8.2.1 and we are moving to 0.9, so new consumer is exactly what we are looking forward to!

Will the "new riemann-kafka" be a new project in order to keep backward compatibility or will it be current project?

**Comment by pyr** [comment]
Hi,

I intend to work with branches on the same repo and tag releases accordingly.

**Comment by liuweichu** [comment]
Thanks for information. We'll keep watching this repo :+1: 

About the current issue, I didn't find a way to bypass the explicit commit per message without overwriting the `start-kafka-thread` function. 
In our use case, I redefined the function (thanks to clojure's dynamic nature again) and only rely to the auto commit of consumer.
If you have a better way to achieve to do this without changing the library code, could you please tell me?

Otherwise, as a temporary solution, I would like to make a PR to change this behavior configurable. Should that be fine to you?

**Comment by pyr** [comment]
yes, I'm fine with adding options to the current function.

**Comment by liuweichu** [comment]
Thank you very much!
